# -*- coding: utf-8 -*-
# Generated by Django 1.10rc1 on 2016-10-09 19:14
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161009_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
